# Generated by Django 4.1.2 on 2022-10-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('horror', 'horror'), ('fiction', 'fiction'), ('science', 'science'), ('literature', 'literature'), ('blog', 'blog')], default='blog', max_length=30),
        ),
    ]
